---
title: "Machine Learning Course Project"
author: "Zelepukin Dmitriy"
date: "12 august 2017"
output:
  html_document: default
  pdf_document: default
---
The goal of this project is to predict the manner in which they did the exercise. This is the "classe" variable in the training set. 

#Load libraries and data sets
```{r setup, include=FALSE}
library(rpart)
library(rattle)
library(randomForest) # random forest
train <- read.csv('pml-training.csv', stringsAsFactors=F, na.strings = c("NA", "", "#DIV/0!"))
test <- read.csv('pml-testing.csv', stringsAsFactors=F, na.strings = c("NA", "", "#DIV/0!"))
```

# There is need to prepare data for a random forest method
```{r precleaning}
train <- train[,-c(1:7)]
table(train$classe)

new.names <- c("classe")

for(i in names(train)[1:152]){
    
    #--- step 1
    share.na <- round(sum(is.na(train[,i]))*100/19622,2)
    print(paste0(i, " has NAs: ", share.na, "%"))
    
    #--- step 2
    if(share.na==0){
        new.names<-c(new.names,i)
    }
}

new.train <- train[,new.names]
new.train$classe <- as.factor(new.train$classe)
table(new.train$classe)
```

Random Forest method prediction - training and checking
---------------
```{r randforest}
RF <- randomForest(classe~.,data=new.train)
RF.pred <- predict(RF, newdata=test)

#--- variables importance
importance(RF)
varImpPlot(RF)
RF.pred
```

